//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsMemoribilia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsMemoribiliaStoreEntities : DbContext
    {
        public SportsMemoribiliaStoreEntities()
            : base("name=SportsMemoribiliaStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MLB> MLBs { get; set; }
        public virtual DbSet<NBA> NBAs { get; set; }
        public virtual DbSet<NFL> NFLs { get; set; }
        public virtual DbSet<NHL> NHLs { get; set; }
    }
}
